<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="measure" nsURI="http://blackbelt.hu/judo/meta/measure" nsPrefix="measure">
  <eClassifiers xsi:type="ecore:EClass" name="Measure" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//Unit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateDividend" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateDivisor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedMeasure" eSuperTypes="#//Measure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" lowerBound="1" upperBound="-1"
        eType="#//BaseMeasureTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseMeasure" eSuperTypes="#//Measure"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaseMeasureTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exponent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseMeasure" lowerBound="1"
        eType="#//BaseMeasure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DurationType">
    <eLiterals name="millisecond"/>
    <eLiterals name="second" value="1"/>
    <eLiterals name="minute" value="2"/>
    <eLiterals name="hour" value="3"/>
    <eLiterals name="day" value="4"/>
    <eLiterals name="week" value="5"/>
    <eLiterals name="month" value="6"/>
    <eLiterals name="year" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DurationUnit" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DurationType"/>
  </eClassifiers>
</ecore:EPackage>
